version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sharedrop
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 900
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
